hospital/hospital/urls.py
from django.contrib import admin
from django.urls import path
from app import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('',views.signup,name='signup'),
    path('login/',views.userlogin,name='login'),
    path('addpost/',views.addpost,name='addpost'),
    path('logout/',views.userlogout,name='logout'),
    path('updatepost/<int:id>/',views.updatepost,name='updatepost'),
    path('deletepost/<int:id>',views.deletepost,name='deletepost'),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

hospital/app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
USER_CHOICE=(
    ('Doctor','Doctor'),
    ('Patient','Patient'),
)
STATE_CHOICES=(
    ('Andaman & Nikobar Islands','Andaman & Nicobar Islands'),
    ('Andhra Pradesh','Andhra Pradesh'),
    ('Arunachal Pradesh','Arunachal Pradesh'),
    ('Assam','Assam'),
    ('Bihar','Bihar'),
    ('Chandigarh','Chandigarh'),
    ('Chhattisgarh','Chhattisgarh'),
    ('Dadra & Nagar Haveli','Dadra & Nagar Haveli'),
    ('Daman and Diu','Daman and Diu'),
    ('Delhi','Delhi'),
    ('Goa','Goa'),
    ('Gujarat','Gujarat'),
    ('Haryana','Haryana'),
    ('Himachal Pradesh','Himachal Pradesh'),
    ('Jammu & Kashmir','Jammu & Kashmir'),
    ('Jharkhand','Jharkhand'),
    ('Karnataka','Karnataka'),
    ('Kerala','Kerala'),
    ('Lakshadweep','Lakshadweep'),
    ('Madhya Pradesh','Madhya Pradesh'),
    ('Maharashtra','Maharashtra'),
    ('Manipur','Manipur'),
    ('Meghalaya','Meghalaya'),
    ('Mizoram','Mizoram'),
    ('Nagaland','Nagaland'),
    ('Odisha','Odisha'),
    ('Puducherry','Puducherry'),
    ('Punjab','Punjab'),
    ('Rajasthan','Rajasthan'),
    ('Sikkim','Sikkim'),
    ('Tamil Nadu','Tamil Nadu'),
    ('Telangana','Telangana'),
    ('Tripura','Tripura'),
    ('Uttarakhand','Uttarakhand'),
    ('Uttar Pradesh','Uttar Pradesh'),
    ('West Bengal','West Bengal'),
)

class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    profile_pic=models.ImageField(upload_to='profileimg',default='profileimg/default.jpg',blank=True)
    type=models.CharField(choices=USER_CHOICE,max_length=20)
    line=models.CharField(max_length=100)
    city=models.CharField(max_length=50)
    state=models.CharField(choices=STATE_CHOICES,max_length=50)
    pincode=models.IntegerField()

hospital/app/templates/app/addpost.html
{% extends 'app/base.html' %}
{% load static %}
{% block content %}
<div class="col-sm-10">
    <h3 class="text-white my-5">Dashboard/ Add Profile</h3>
    <form action="" method="POST">
        {% if messages %}
        {% for message in messages %}
        <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %} mt-3" role="alert">{{message}}</div>
        {% endfor %}
        {% endif %}
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" class="btn btn-success" value="Add Post">
        <a href="{% url 'dashboard' %}" class="btn btn-primary">Cancel</a>
        <!-- {% if messages %}
            {% if message in messages %}
                {{messages}}
            {% endif %}
        {% endif%} -->
        
    </form>
</div>
{% endblock content %}

hospital/app/templates/app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hospital</title>
    <link rel="stylesheet" href="{% static 'app/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/style.css' %}">
    <style>
        body{
            background-color: coral;
        }
    </style>
</head>
<body>
    <div class="container-fluid bg-dark">
        {% include 'app/navbar.html' %}
    </div>
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                {% block msg %}
                {% endblock msg %}
            </div>
        </div>
        <div class="row">
            {% block side %}
            {% endblock side %}

            {% block content %}
            {% endblock content %}
        </div>
    </div>
    <script src="{% static 'app/js/jquery.js' %}"></script>
    <script src="{% static 'app/js/popper.js' %}"></script>
    <script src="{% static 'app/js/bootstrap.js' %}"></script>
</body>
</html>

hospital/app/templates/app/dashboard.html
{% extends 'app/base.html' %}
{% load static %}
{% block side %}
<div class="border-right border-warning h-100">Name</div>
<h3>{{name}} {{name2}}</h3>
<div class="text-center">
  {% for post in posts %}
  <img src="{{post.profile_pic.url}}" alt="profile pic" class="img-thumbnail" width="250px" height="150px">
  {% endfor %}
</div>
{% endblock side %}
{% block content %}

<div class="col-sm-10">
  {% if messages %}
  {% for message in messages %}
      <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %} mt-3" role="alert">{{message}}</div>
  {% endfor %}
{% endif %}
    <h3 class="text-dark">Dashboard Page</h3>
    {% if perms.app.add_profile %}
    <a href="{% url 'addpost' %}" class="btn btn-success">Add Profile</a>
    {% endif %}
    <div class="container">
        <table class="table caption-top text-white">
            <caption class="text-center">List of Posts</caption>
            <thead>  
              <tr>
                <th scope="col">ID</th>
                <th scope="col">User</th>
                <th scope="col">Type</th>
                <th scope="col">Address</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
                {% for post in posts %}
              <tr>
                <th scope="row">{{post.id}}</th>
                <td>{{post.user}}</td>
                <td>{{post.type}}</td>
                <td>{{post.line}} {{post.city}} {{post.state}} {{post.pincode}}</td>
                <td>
                {% if perms.app.change_profile %}
                <a href="{% url 'updatepost' post.id %}" class="btn btn-warning">Edit</a>
                {% endif %}
                {% if perms.app.delete_profile %}
                <form action="{% url 'deletepost' post.id %}" method="post">
                    {% csrf_token %}
                    <input type="submit" class="btn btn-danger btn-sm mt-2" value="Delete">
                </form>
                {% endif %}
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
    </div>


</div>

{% endblock content%}

hospital/app/templates/app/login.html
{% extends 'app/base.html' %}
{% load static %}
{% block content %}
<div class="col-sm-10">
    <h3 class="text-white">Login Page</h3>
    <form action="" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Login" class="btn btn-primary">
        <!-- <a href="" class="btn btn-secondary">Forgot Password</a> -->
    </form>
</div>
{% endblock content%}

hospital/app/templates/app/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="">Medical</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'dashboard' %}">Dashboard</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'signup' %}">Signup</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

hospital/app/templates/app/signup.html
{% extends 'app/base.html' %}
{% load static %}
{% block content %}

<div class="col-sm-10">
    <h3 class="text-white">Signup Page</h3>
    <form action="" method="POST">
        {% if messages %}
        {% for message in messages %}
        <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %} mt-3" role="alert">{{message}}</div>
        {% endfor %}
        {% endif %}
        {% csrf_token %}
        {% for fm in form %}
            {{fm.label_tag}} {{fm}} {{fm.errors|striptags}}<br><br>
        {% endfor %}
        <input type="submit" value="Signup" class="btn btn-primary">
        
    </form>

</div>

{% endblock content%}

hospital/app/templates/app/updatepost.html
{% extends 'app/base.html' %}
{% load static %}
{% block content %}
<div class="col-sm-10">
    <h3 class="text-white my-5">Dashboard/ Update Profile</h3>
    <form action="" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" class="btn btn-success" value="Add Post">
        <a href="{% url 'dashboard' %}" class="btn btn-primary">Cancel</a>
    </form>
</div>
{% endblock content %}